# Documentation: https://roots.io/trellis/docs/vault/
vault_mysql_root_password: "generateme"

# Cloudflare Origin CA
vault_cloudflare_origin_ca_key: generateme_from_cloudflare

# Documentation: https://roots.io/trellis/docs/security/
vault_users:
  - name: "{{ admin_user }}"
    password: "Aman@31AK"
    salt: "generateme"

# Variables to accompany `group_vars/staging/wordpress_sites.yml`
# Note: the site name (`example.com`) must match up with the site name in the above file.
vault_wordpress_sites:
  neticians.com:
    env:
      db_password: "Aman@31AK"
      # Generate your keys here: https://roots.io/salts.html
      auth_key: "generateme"
      secure_auth_key: "generateme"
      logged_in_key: "generateme"
      nonce_key: "generateme"
      auth_salt: "generateme"
      secure_auth_salt: "generateme"
      logged_in_salt: "generateme"
      nonce_salt: "generateme"
  htpasswd:
      - name: amankapoor
        password: "Aman@31AK"
      - name: neticians.com
        password: "Customer@123"
