# Documentation: https://roots.io/trellis/docs/remote-server-setup/
# `wordpress_sites` options: https://roots.io/trellis/docs/wordpress-sites
# Define accompanying passwords/secrets in group_vars/staging/vault.yml

wordpress_sites:
  neticians.com:
    site_hosts:
      - canonical: staging.neticians.com
        # redirects:
        #   - otherdomain.com
    local_path: ../site # path targeting local Bedrock site directory (relative to Ansible root)
    repo: git@github.com:amankapoor/neticians.com.git # replace with your Git repo URL
    repo_subtree_path: site # relative path to your Bedrock/WP directory in your repo
    branch: master
    multisite:
      enabled: false
    ssl:
      enabled: true
      stapling_enabled: false
      provider: cloudflare-origin-ca
    cloudflare_origin_ca:
      days: 5475
      hostnames:
        - neticians.com
        - "*.neticians.com"
      key_size: 256
      key_type: ecdsa #THIS WILL BE IN RSA FORMAT IF SHARED HOSTING IS BEING USED
    cache:
      enabled: true
      duration: 30s
      skip_cache_uri: /wp-admin/|/xmlrpc.php|wp-.*.php|/feed/|index.php|sitemap(_index)?.xml|/store.*|/cart.*|/my-account.*|/checkout.*|/addons.*
      skip_cache_cookie: comment_author|wordpress_[a-f0-9]+|wp-postpass|wordpress_no_cache|wordpress_logged_in|woocommerce_cart_hash|woocommerce_items_in_cart|wp_woocommerce_session_
    htpasswd:
      - name: amankapoor
        password: "Aman@31AK"
      - name: neticians.com
        password: "Customer@123"